name: ZachSmithBobyardChallenge
channels:
  - defaults
dependencies:
  - bzip2
  - ca-certificates
  - django=4.1
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.12
  - pip=23.3.1
  - python=3.11.5
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - sqlparse=0.4.4
  - tk=8.6.12
  - tzdata=2023c
  - wheel=0.41.2
  - xz=5.4.5
  - zlib=1.2.13
  - pip:
      - asgiref==3.7.2
      - django-cors-headers==4.3.1
      - djangorestframework==3.14.0
      - psycopg2-binary==2.9.9
      - pytz==2023.3.post1
      - urllib3==1.26.6
